### ISSUE TITLE
Console has been discconnected from server by timeout

### ISSUE THREAD

**Issue by ruslalnSkiselev** [cuba-platform/admin-tools-addon#1]
**Steps to reproduce:**
 1. Input non-existent Host.
 2. Press [Connect].
 3. Waiting for a timeout
 4. Input a valid Host.
 3. Press [Connect].
**ER:**
Connected
**AR:**
Console has been discconnected from server by timeout

**Comment by slogan163** [comment]
It is not correct  test case

**Comment by slogan163** [comment]
can't reproduce
