### ISSUE TITLE
Do not override logic of EntityImportViewBuilder

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/admin-tools-addon#12]
`ExtendedEntityImportViewBuilder` breaks the logic of saving entities through REST API.

If you need this functionality, register your `ExtendedEntityImportViewBuilder` with a different bean name and use [these recommendations](https://stackoverflow.com/questions/10534053/autowiring-two-beans-implementing-same-interface-how-to-set-default-bean-to-au) to keep both beans in the context.

**Comment by slogan163** [comment]
fixed
