### ISSUE TITLE
Add predefined roles

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/admin-tools-addon#30]
### Environment

- Platform version: 7.2.x
- Addon version: 1.5-SNAPSHOT

### Description

Create predefined system roles

**Comment by zaharchenko-evgeny** [comment]
# Predefined roles

- **Admin tools full access** - full access to admin tools add-on features
- **Admin tools diagnose** - ability to upload diagnose info in admin tools diagnose wizard

**Comment by skatova** [comment]
For **Admin tools full access** role:
1. Click Administration → Admin tools → SQL Script Generator
2. Select Script Type = Insert (or Update, or Insert update) , Entity Type = sec$User, View = _local
3. Click Generate
E.R. The script was generated
A.R. No data found
![image](https://user-images.githubusercontent.com/53561930/80491907-601dd180-8974-11ea-92db-23eaef2e016e.png)

**Comment by zaharchenko-evgeny** [comment]
This is expected behaviour, a user should have extra privileges to read data
