### ISSUE TITLE
Scrambled screen elements on a reduced screen size

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/admin-tools-addon#6]
On my 15" laptop:
![image](https://user-images.githubusercontent.com/5513878/38558537-803d729a-3ce1-11e8-8a30-a5558017145d.png)

Also, make a horizontal split between Query and Result.

**Comment by slogan163** [comment]
fixed

**Comment by knstvk** [comment]
Put issue number in commit messages, e.g. "Fixed scrambled screen elements on a reduced screen size #6". Then we'll see commits here.

**Comment by slogan163** [comment]
commit messages have changed
