### ISSUE TITLE
Wrong text about upload directory in Config Loader

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/admin-tools-addon#7]
![image](https://user-images.githubusercontent.com/5513878/38559051-07ce4e22-3ce3-11e8-8297-6283cdb05959.png)

At the same time, README tells that "The location of the configuration directory is determined by the cuba.confDir application property." and the screenshot shows different path.

In fact, the files in dev environment are uploaded to `tomcat/conf`, which does not conform neither to the first statement nor second.

**Comment by slogan163** [comment]
changed to 'tomcat/conf' in all resources
