### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by knstvk** [cuba-platform/admin-tools-addon#8]
- Place addon components in the order of their appearance in menu
- Fix screenshots, they do not correspond to reality
- "allows to do smth" -> "allows **someone** to do smth", e.g "allows **you** to". Or "enables to do smth".
- "JMX Tomcat" -> "Tomcat JMX"
- "allows operating with Tomcat" - "allows you to execute operations with Tomcat server currently running the application"
- "There are two objects: TomcatCore for operating with a core module and TomcatWeb for operating with web module." - what does it mean?

**Comment by slogan163** [comment]
fixed
